export const datax = [
  {
    _id: "16",
    name: "Green Top with Puff Sleeves",
    desc: "Green top with puff sleeves and an all-over print of small floral or star motifs, paired with blue jeans and white sneakers. A simple and casual look.",
    price: 10.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "western",
    image: "/items/western/wes1.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "17",
    name: "Zigzag Patterned Crop Top ",
    desc: "Red and white zigzag patterned crop top with long sleeves, styled with white pants and showing some midriff. A vibrant and striking top",
    price: 15.0,
    oldPrice: 0,
    stock: 25,
    sold: 25,
    totalStars: 0,
    type: "western",
    image: "/items/western/wes2.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },

  {
    _id: "18",
    name: "Top with Bell Sleeves",
    desc: "Multicolored striped, loose-fitting top with bell sleeves, worn with white pants and flat sandals. A bold, breezy look incorporating several colors.",
    price: 8.0,
    oldPrice: 10.0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "western",
    image: "/items/western/wes3.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "19",
    name: "Long-Sleeved Crop Top",
    desc: "Black off-the-shoulder long-sleeved crop top paired with white high-waisted pants and black slide sandals. A chic, midriff-baring ensemble in classic colors.",
    price: 10.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "western",
    image: "/items/western/wes4.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "20",
    name: "Light Blue Top",
    desc: "Light blue top with a white polka dot pattern and short sleeves, worn with white pants. A simple, feminine casual outfit in soft hues.",
    price: 20.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "western",
    image: "/items/western/wes5.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "21",
    name: "Red Off-The-Shoulder Crop Top",
    desc: "Red off-the-shoulder crop top with floral patterns and tie details on the short sleeves. She is also wearing white high-waisted jeans or pants.",
    price: 18.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "western",
    image: "/items/western/wes6.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "22",
    name: "Red Camisole",
    desc: "Red spaghetti strap crop top or camisole. She is also wearing white high-waisted jeans or pants and has visible tattoos on her arm.",
    price: 20.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "western",
    image: "/items/western/wes7.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },

  {
    _id: "23",
    name: "Checkered Top",
    desc: "Black and white checkered or patterned sleeveless top with a V-neckline. She is also wearing white high-waisted jeans or pants.",
    price: 60.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "western.jpg",
    image: "items/western/wes8.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "24",
    name: "Embroidered Floral Top",
    desc: "Sage green flowy blouse or top with ruffled sleeves and embroidered floral detailing. She is also wearing white high-waisted jeans or pants.",
    price: 10.0,
    oldPrice: 15.0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "western.jpg",
    image: "items/western/wes9.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "25",
    name: "Black Romper",
    desc: "Black strapless jumpsuit or romper with a purple ruffle or cape detail on one shoulder. She is also wearing black high-waisted wide-leg pants.",
    price: 40.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "western.jpg",
    image: "items/western/wes10.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "26",
    name: "Form-Fitting Purple Dress",
    desc: "Form-fitting purple dress that goes down to her knees. She has long brown hair and is wearing black high-heeled sandals.",
    price: 70.0,
    oldPrice: 0,
    stock: 35,
    sold: 4,
    totalStars: 0,
    type: "western",
    image: "items/western/wes11.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "27",
    name: "Black Off-The-Shoulder Dress",
    desc: "Black off-the-shoulder dress with a ruffle detail across the neckline. The dress is knee-length, and she is wearing the same black high-heeled sandals.",
    price: 40.0,
    oldPrice: 0,
    stock: 30,
    sold: 0,
    totalStars: 0,
    type: "western",
    image: "items/western/wes12.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "28",
    name: "Red Lace Off-The-Shoulder Dress",
    desc: "Red lace off-the-shoulder dress that hits above the knee. She has her hands folded in front of her and is wearing black high-heeled sandals.",
    price: 30.0,
    oldPrice: 0,
    stock: 30,
    sold: 0,
    totalStars: 0,
    type: "western",
    image: "items/western/wes13.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "29",
    name: "White Sleeveless Dress",
    desc: "White sleeveless dress with vertical stripes and buttons down the front. The dress is knee-length, and she is wearing black high-heeled sandals.",
    price: 10.0,
    oldPrice: 0,
    stock: 50,
    sold: 24,
    totalStars: 0,
    type: "western",
    image: "items/western/wes14.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "30",
    name: "Short Sleeve and Flared Skirt",
    desc: "Red lace dress with short sleeves and a flared skirt that goes below the knee. She has her hands on her hips and is wearing black high-heeled sandals.",
    price: 14.0,
    oldPrice: 0,
    stock: 40,
    sold: 0,
    totalStars: 0,
    type: "western",
    image: "items/western/wes15.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
];

export const dataxVeggies = [
  {
    _id: "1",
    name: "Red & Pink Salwar Suit",
    desc: "Red and pink collide in this salwar suit, offering a vibrant playfulness with a touch of elegance.",
    price: 350.0,
    oldPrice: 0,
    stock: 10,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth1.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "2",
    name: "Orange Embroidered Kurta",
    desc: "A splash of citrus! This orange kurta pops with vibrant color and boasts intricate embroidery for a touch of timeless elegance.",
    price: 99.0,
    oldPrice: 0,
    stock: 10,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth2.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "3",
    name: "Red A-Line Kurta",
    desc: "Flattering A-line silhouette in a fiery red, this kurta exudes confidence and timeless style.",
    price: 140.0,
    oldPrice: 0,
    stock: 10,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth3.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "4",
    name: "Cream and Pink Kurta",
    desc: "This cream and pink kurta blends delicate elegance with a touch of sweetness, offering a versatile piece for any occasion.",
    price: 250.0,
    oldPrice: 0,
    stock: 10,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth4.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "5",
    name: "Embroidered Chanderi Frontslit Kurta",
    desc: "Delicately embroidered Chanderi kurta with a front slit, adding a touch of elegance and modern flair.",
    price: 75.0,
    oldPrice: 0,
    stock: 10,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth5.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "6",
    name: "Cottom Straight Kurta",
    desc: "Crafted in cool comfort, this cotton straight kurta offers a timeless silhouette for everyday elegance.",
    price: 140.0,
    oldPrice: 0,
    stock: 10,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth6.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },

  {
    _id: "7",
    name: "Colourblock Straight Kurta",
    desc: "Bold geometric patterns come alive in this colorblock straight kurta, making a statement with a contemporary twist.",
    price: 120.0,
    oldPrice: 0,
    stock: 10,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth7.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "8",
    name: "Flared A-Line Gown",
    desc: "This flowing A-line gown cascades gracefully, offering a touch of drama and timeless elegance.",
    price: 40.0,
    oldPrice: 65.0,
    stock: 15,
    sold: 9,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth8.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "9",
    name: "Black slit-cut Kurti",
    desc: "King Prawns are almost pure protein with little fat. 100 grams of cooked King Prawns is approximately 70 calories with 15 grams of protein.",
    price: 175.0,
    oldPrice: 0,
    stock: 15,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth9.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "10",
    name: "Red Viscose Rayon Anarkali",
    desc: "Flowing elegance in fiery red, this viscose rayon Anarkali drapes beautifully for a touch of timeless sophistication.",
    price: 450.0,
    oldPrice: 0,
    stock: 15,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth10.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "11",
    name: "Cotton Handloom Kura",
    desc: "This handloom cotton kurta offers a touch of tradition and everyday comfort in a breathable, handwoven fabric.",
    price: 30.0,
    oldPrice: 40.0,
    stock: 20,
    sold: 8,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth11.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "12",
    name: "Polka Dot High-slit Kurta",
    desc: "Channel playful elegance with a polka dot high-slit kurta, offering a modern twist on a classic silhouette.",
    price: 250.0,
    oldPrice: 0,
    stock: 20,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth12.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "13",
    name: "Printed Salwar Suit",
    desc: "Vibrant or subtle, a printed salwar suit brings a touch of artistic flair to your traditional attire.",
    price: 120.0,
    oldPrice: 150.0,
    stock: 30,
    sold: 11,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth13.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },

  {
    _id: "14",
    name: "Navy Straight Acrylic Kurta",
    desc: "Tailored for comfort in a classic silhouette, this navy straight acrylic kurta offers everyday versatility.",
    price: 8.0,
    oldPrice: 9.0,
    stock: 10,
    sold: 9,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth14.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "15",
    name: "Floral A-Line Kurta",
    desc: "Bloom with elegance in this floral A-line kurta, offering a touch of femininity and flattering form.",
    price: 15.0,
    oldPrice: 0,
    stock: 20,
    sold: 0,
    totalStars: 0,
    type: "ethnic",
    image: "/items/ethnic/eth15.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
];

export const dataInfo = [
  {
    image: "/home/scooter.svg",
    first: "Free Delivery Across the US!",
    second: "Free delivery for all orders above $100",
  },
  {
    image: "/home/heart.svg",
    first: "100% Satisfaction Guarantee!",
    second: "Providing help in case of dissatisfaction",
  },
  {
    image: "/home/chat.svg",
    first: "Top-Notch Support",
    second: "Chat with us if you’ve any questions",
  },
  {
    image: "/home/card.svg",
    first: "Secure Payments",
    second: "We use safest payment technologies",
  },
];

const stripetestingdata = {
  cardno: "4242 4242 4242 4242",
};
